branches:
  - name: main
    protection:
      required_status_checks:
        strict: true
        contexts: ["lint", "security", "test", "trivy-scan"]
      enforce_admins: true
      required_pull_request_reviews:
        required_approving_review_count: 1