name: Security Scans

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  trivy-container-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: aquasecurity/trivy-action@master
        with:
          image-ref: ghcr.io/${{ github.repository }}:latest

  codeql:
    uses: github/codeql-action/analyze@v3
